openapi: 3.1.1
paths:
  /course:
    description: API to provide CRUD operations for managing course data
    get:
      operationId: get-course-list
      description: API to fetch course list or one course by id
      parameters:
        - $ref: '../openapi-spec.yaml#/components/parameters/page_number'
        - $ref: '../openapi-spec.yaml#/components/parameters/page_size'
        - $ref: '#/components/parameters/course_id'
      responses:
        default:
          $ref: '../openapi-spec.yaml#/components/responses/defaultResponse'
        "200":
          description: The course list is returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseResponseDTO'
    post:
      operationId: save-course-record
      description: API to save new course
      requestBody:
        description: Request model to save course
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseRequestDTO'
      responses:
        default:
          $ref: '../openapi-spec.yaml#/components/responses/defaultResponse'
        "201":
          description: New course record is saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseResponseDTO'
    patch:
      operationId: update-course-record
      description: API to update Course if present
      requestBody:
        description: Request model to update course
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseRequestDTO'
      parameters:
        - $ref: '#/components/parameters/course_id'
      responses:
        default:
          $ref: '../openapi-spec.yaml#/components/responses/defaultResponse'
        "202":
          description: Course record details are updated
    delete:
      operationId: delete-course-record
      parameters:
        - $ref: '#/components/parameters/course_id'
      responses:
        default:
          $ref: '../openapi-spec.yaml#/components/responses/defaultResponse'
        "204":
          description: Course record details are deleted
components:
  parameters:
    course_id:
      name: course_id
      in: header
      description: Unique id to identify course
      required: true
      schema:
        type: integer
        format: int64
  schemas:
    CourseResponseDTO:
      title: CourseResponseDTO
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique ID for the course record
        name:
          type: string
          description: Name of the Course
        createdAt:
          type: offsetDateTime
          description: The date the course was created at
        faculty:
          $ref: '../faculty/faculty-spec.yaml#/components/schemas/FacultyResponseDTO'
    CourseRequestDTO:
      title: CourseRequestDTO
      type: object
      properties:
        name:
          type: string
          description: Name of the Course
        createdAt:
          type: offsetDateTime
          description: The date the course was created at
        facultyId:
          type: integer
          format: int64
          description: Unique ID for the faculty owning the course