openapi: 3.1.1
info:
  title: Online Coding Test Service
  summary: APIs to provide API access to online coding test service
  version: 1.0.0
servers:
  - url: "{scheme}://{hostname}:{port}/api/coding/test/service"
    description: The base path for the API
    variables:
      scheme:
        enum:
          - "https"
          - "http"
        default: "http"
      hostname:
        enum:
          - "localhost"
        default: "localhost"
      port:
        enum:
          - "8080"
          - "443"
        default: "8080"
paths:
  $ref: "./faculty/faculty-spec.yaml#/paths"
components:
  responses:
    defaultResponse:
      description: Default response for unhandled errors
      content:
        application/json:
          schema:
            type: problemDetail
            externalDocs:
              description: Spring ProblemDetail object
              url: https://docs.spring.io/spring-framework/reference/web/webflux/ann-rest-exceptions.html
  parameters:
    page_number:
      name: page_number
      in: query
      description: The page number to return if fetching all records
      required: false
      schema:
        type: integer
        format: int32
        default: 1
    page_size:
      name: page_size
      in: query
      description: The number of records in a single page
      required: false
      schema:
        type: integer
        format: int32
        default: 10