openapi: 3.1.1
paths:
  /enrollment:
    description: API to provide CRUD operations for managing Enrollment data
    get:
      operationId: get-enrollment-list
      description: API to fetch Enrollment list or one enrollment by id
      parameters:
        - $ref: '../openapi-spec.yaml#/components/parameters/page_number'
        - $ref: '../openapi-spec.yaml#/components/parameters/page_size'
        - $ref: '#components/parameters/enrollment_id'
      responses:
        default:
          $ref: '../openapi-spec.yaml#/components/responses/defaultResponse'
        "200":
          description: The enrollment list is returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnrollmentResponseDTO'
    post:
      operationId: save-enrollment-record
      description: API to save new enrollment for enrollment
      requestBody:
        description: Request model to save enrollment
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrollmentRequestDTO'
      responses:
        default:
          $ref: '../openapi-spec.yaml#/components/responses/defaultResponse'
        "201":
          description: New enrollment record is saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentResponseDTO'
    patch:
      operationId: update-enrollment-record
      description: API to update enrollment if present
      requestBody:
        description: Request model to update enrollment
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrollmentRequestDTO'
      parameters:
        - $ref: '#/components/parameters/enrollment_id'
      responses:
        default:
          $ref: '../openapi-spec.yaml#/components/responses/defaultResponse'
        "202":
          description: Enrollment record details are updated
    delete:
      operationId: delete-enrollment-record
      parameters:
        - $ref: '#/components/parameters/enrollment_id'
      responses:
        default:
          $ref: '../openapi-spec.yaml#/components/responses/defaultResponse'
        "204":
          description: Enrollment record details are deleted
components:
  parameters:
    enrollment_id:
      name: enrollment_id
      in: header
      description: Unique id to identify course
      required: true
      schema:
        type: integer
        format: int64
  schemas:
    EnrollmentResponseDTO:
      title: EnrollmentResponseDTO
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique ID for the course record
        student:
          $ref: '../student/student-spec.yaml#/components/schemas/StudentResponseDTO'
        status:
          type: string
          description: The status of the enrollment
        course:
          $ref: '../course/course-spec.yaml#/components/schemas/CourseResponseDTO'
    EnrollmentRequestDTO:
      title: EnrollmentRequestDTO
      type: object
      properties:
        student:
          type: integer
          format: int64
          description: Unique ID to identify the student
        status:
          type: string
          description: The status of the enrollment
        course:
          type: integer
          format: int64
          description: Unique ID to identify the course